### ISSUE TITLE
Inject error reporting in demo code

### ISSUE THREAD

**Issue by jiang95-dev** [GoogleCloudPlatform/stackdriver-sandbox#131] opened 2020-07-16 01:05 UTC
To use the Error Reporting UI requires us to either call a client library to report errors, or format the log so that it can be digested by Cloud Logging. Both need us to explicitly inject it in the demo code. 

One way to simulate the error generation is to trigger an error in some function of some service with probability. Another way is to create a service specifically causing errors when requests are made.

**Comment by simonz130** [comment] 2020-07-23 05:30
Closing as a dupe of #53

**Closed by simonz130** 2020-07-23 05:30 UTC
Labels: lang: shell, priority: p2, type: process
